version: '3.8'

services:
  my_postgres:
    image: postgres:14.11
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./src/main/js/database/migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    # networks:
    #   - mqtt-network

  app_build:
    image: node:18.19.0-buster
    volumes:
      - .:/opt
    working_dir: /opt
    command: ["npm", "install"]
    depends_on:
      - my_postgres
    # networks:
    #   - mqtt-network
    environment:
      - BROKER_HOST=rabbit

  # migration:
  #   image: node:18.19.0-buster
  #   volumes:
  #     - .:/opt
  #   working_dir: /opt
  #   command: ["node", "src/main/js/database/migration/202401261523_create_mesures_poids_tables.js"]
  #   depends_on:
  #     - my_postgres
  #   # networks:
  #   #   - mqtt-network
  #   environment:
  #     - BROKER_HOST=rabbit

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - my_postgres
    # networks:
    #   - mqtt-network

  subscriber:
    image: node:18.19.0-buster
    volumes:
      - .:/opt
    working_dir: /opt
    command: ["node", "src/main/js/subscribe/client.js"]
    depends_on:
      - rabbit
      - my_postgres
    # networks:
    #   - mqtt-network
    environment:
      - BROKER_HOST=rabbit

  alarms:
    image: node:18.19.0-buster
    volumes:
      - .:/opt
    working_dir: /opt
    command: ["node", "src/main/js/subscribe/alarms.js"]
    depends_on:
      - rabbit
      - my_postgres
    # networks:
    #   - mqtt-network
    environment:
      - BROKER_HOST=rabbit

  publisher:
    image: node:18.19.0-buster
    volumes:
      - .:/opt
    working_dir: /opt
    command: ["node", "src/main/js/publisher/bac.js"]
    depends_on:
      - rabbit
    # networks:
    #   - mqtt-network
    environment:
      - BROKER_HOST=rabbit
# networks:
#   mqtt-network:
#     driver: bridge

  api:
    image: node:18.19.0-buster
    volumes:
      - .:/opt
    working_dir: /opt
    command: ["node", "src/main/js/api/index.js"]
    depends_on:
      - my_postgres
    # networks:
    #   - mqtt-network
    environment:
      - BROKER_HOST=rabbit

volumes:
  postgres_data2:
