#!/bin/bash

if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0
fi

RABBIT_HOST=rabbit
NETWORK_NAME=mqtt-network

if [ ! "$(docker network ls | grep "$NETWORK_NAME")" ]; then
  echo "Creating network ..."
  docker network create $NETWORK_NAME
fi

docker run -d --rm --name $RABBIT_HOST -p 5672:5672 -p 15672:15672 --net $NETWORK_NAME rabbitmq:3-management
